name = input("Введите Ваше имя: ")
title_1 = input("Основные темы: ")
title_2 = input("Персонажи: ")
title_3 = input("Рекомендации для чтения: ")
title = [title_1, title_2, title_3]
print(title)
content = input("О чем Ваша заметка? ")
status = input("Какой статус заметки? ")
created_date = input("Укажите дату создания (в формате ДД-ММ-ГГГГ) ")
issue_date = input("Укажите дату истечения (в формате ДД-ММ-ГГГГ) ")